import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "it";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Hero
    heroTitle: "AI-Powered Survey Generator",
    heroSubtitle: "Transform your ideas or documents into professional Google Forms surveys in seconds. Let AI do the heavy lifting.",
    getStarted: "Get Started Free",
    lightningFast: "Lightning Fast",
    lightningFastDesc: "Generate complete surveys in seconds with AI",
    documentToSurvey: "Document to Survey",
    documentToSurveyDesc: "Upload Word or PDF documents to auto-generate surveys",
    readyForGoogleForms: "Ready for Google Forms",
    readyForGoogleFormsDesc: "Export-ready format for seamless integration",
    
    // Auth
    login: "Log In",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    logout: "Log Out",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signupSuccess: "Account created successfully!",
    loginSuccess: "Logged in successfully!",
    invalidCredentials: "Invalid email or password",
    passwordsNotMatch: "Passwords do not match",
    emailRequired: "Email is required",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
    
    // Dashboard
    myQuestionnaires: "My Questionnaires",
    createNew: "Create New Questionnaire",
    active: "Active",
    inactive: "Inactive",
    expired: "Expired",
    responses: "Responses",
    edit: "Edit",
    delete: "Delete",
    activate: "Activate",
    deactivate: "Deactivate",
    copyLink: "Copy Link",
    extendExpiration: "Extend Expiration",
    viewResponses: "View Responses",
    createdOn: "Created on",
    expiresOn: "Expires on",
    noExpiration: "No expiration",
    noQuestionnaires: "No questionnaires yet",
    createFirstQuestionnaire: "Create your first questionnaire to get started",
    deleteConfirm: "Delete Questionnaire",
    deleteConfirmMsg: "Are you sure you want to delete this questionnaire? This action cannot be undone.",
    linkCopied: "Link copied!",
    linkCopiedDesc: "Survey link has been copied to clipboard",
    surveyDeleted: "Survey deleted",
    surveyActivated: "Survey activated",
    surveyDeactivated: "Survey deactivated",
    
    // Survey
    submitSurvey: "Submit Survey",
    requiredField: "This field is required",
    surveyExpired: "This survey has expired",
    thankYou: "Thank you!",
    responseSubmitted: "Your response has been submitted",
    surveyNotFound: "Survey not found",
    surveyNotFoundDesc: "The survey you're looking for doesn't exist or has been removed",
    surveyInactive: "Survey Inactive",
    surveyInactiveDesc: "This survey is currently not accepting responses",
    submitting: "Submitting...",
    
    // Save Survey
    saveSurvey: "Save Questionnaire",
    updateSurvey: "Update Questionnaire",
    surveyTitle: "Title",
    surveyTitlePlaceholder: "Enter questionnaire title",
    surveyDescription: "Description",
    surveyDescriptionPlaceholder: "Enter questionnaire description (optional)",
    expirationDate: "Expiration Date (optional)",
    customExpirationMessage: "Custom Expiration Message (optional)",
    customExpirationPlaceholder: "This survey has expired",
    quickOptions: "Quick Options",
    days7: "7 days",
    days30: "30 days",
    noExpirationOption: "No expiration",
    surveySaved: "Questionnaire saved!",
    surveySavedDesc: "Your questionnaire has been saved successfully",
    surveyUpdated: "Questionnaire updated!",
    titleRequired: "Title is required",
    titleRequiredDesc: "Please provide a title for your questionnaire",
    expirationExtended: "Expiration extended",
    expirationRemoved: "Expiration removed",
    pickDate: "Pick a date",
    selectExpirationDate: "Select expiration date",
    removeExpiration: "Remove Expiration",
    
    // Responses
    surveyResponses: "Survey Responses",
    submittedAt: "Submitted at",
    noResponses: "No responses yet",
    noResponsesDesc: "This survey hasn't received any responses yet",
    exportResponses: "Export Responses",
    responsesExported: "Responses exported!",
    
    // Survey Generator
    backToHome: "Back to Home",
    createYourSurvey: "Create Your Survey",
    sections: "sections",
    section: "section",
    totalQuestions: "total questions",
    surveyLanguage: "Survey Language",
    sectionName: "Section Name",
    sectionNamePlaceholder: "Example: Personal Information, Customer Satisfaction, Product Feedback...",
    questionDescription: "Question Description",
    questionDescriptionPlaceholder: "Example: Create questions about product quality, delivery speed and customer service...",
    uploadDocument: "Upload Document",
    chooseFile: "Choose File",
    clear: "Clear",
    supportsFiles: "Supports PDF, Word documents and CSV files",
    csvImported: "CSV Imported",
    imported: "imported",
    invalidCSV: "Invalid CSV",
    csvMustHaveData: "CSV file must contain data",
    invalidCSVFormat: "Invalid CSV Format",
    csvMissingColumns: "CSV must have Section, Question, and Type columns",
    importFailed: "Import Failed",
    failedToImportCSV: "Failed to import CSV file",
    generateFirstSection: "Generate First Section",
    addNewSection: "Add New Section",
    generating: "Generating...",
    yourSurvey: "Your Survey",
    downloadCSV: "Download CSV",
    clearAll: "Clear All",
    removeSection: "Remove Section",
    question: "Question",
    type: "Type",
    multipleChoice: "Multiple choice",
    checkboxes: "Checkboxes",
    shortAnswer: "Short answer",
    paragraph: "Paragraph",
    dropdown: "Dropdown",
    required: "Required",
    options: "Options",
    addOption: "Add Option",
    save: "Save",
    fileUploaded: "File uploaded",
    fileReady: "is ready to be processed",
    invalidFileType: "Invalid file type",
    uploadPDFOrWord: "Please upload a PDF or Word document",
    inputRequired: "Input required",
    provideDescription: "Please provide a description or upload a document",
    sectionNameRequired: "Section name required",
    provideSectionName: "Please provide a name for this section",
    sectionAdded: "Section added!",
    questionsAdded: "questions added to",
    generationFailed: "Generation failed",
    failedToGenerate: "Failed to generate survey. Please try again.",
    csvExported: "CSV exported!",
    importToGoogleForms: "Import this file into Google Forms",
    sectionRemoved: "Section removed",
    hasBeenRemoved: "has been removed",
    allSectionsCleared: "All sections cleared",
    surveyReset: "Survey has been reset",
    questionUpdated: "Question updated",
    changesSaved: "Changes have been saved",
    questionDeleted: "Question deleted",
    questionRemoved: "Question has been removed",
    feedbackLabel: "Feedback for this question",
    feedbackPlaceholder: "Example: Make this question more specific, add more options, change the wording...",
    feedbackHelp: "This feedback helps you understand how questions should be modified and can be used as a model for other questions.",
    feedbackSaved: "Feedback saved",
    feedbackSavedDesc: "Your feedback has been saved for this question",
    generateMore: "Generate more questions",
    newQuestionsAdded: "new questions added to this section",
    applyFeedback: "Apply Feedback",
    extendToOthers: "Extend to Other Questions",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    questionsSelected: "questions selected",
    applying: "Applying...",
    applyingFeedback: "Applying feedback...",
    feedbackApplied: "Feedback applied",
    feedbackAppliedDesc: "The questions have been regenerated",
    cancel: "Cancel",
    noFeedback: "No feedback",
    noFeedbackDesc: "Please add feedback before applying",
    questionsUpdated: "questions updated",
    sourceQuestion: "Source",
    newSectionName: "New Section Name",
    addSection: "Add Section",
    hasBeenCreated: "has been created",
    newSectionDialogDesc: "Generate a new section with AI by providing a title and topic.",
    generateSection: "Generate Section",
  },
  it: {
    // Hero
    heroTitle: "Generatore di Sondaggi con IA",
    heroSubtitle: "Trasforma le tue idee o documenti in sondaggi professionali per Google Forms in pochi secondi. Lascia che l'IA faccia il lavoro pesante.",
    getStarted: "Inizia Gratis",
    lightningFast: "Velocissimo",
    lightningFastDesc: "Genera sondaggi completi in pochi secondi con l'IA",
    documentToSurvey: "Da Documento a Sondaggio",
    documentToSurveyDesc: "Carica documenti Word o PDF per generare automaticamente sondaggi",
    readyForGoogleForms: "Pronto per Google Forms",
    readyForGoogleFormsDesc: "Formato pronto per l'esportazione e l'integrazione perfetta",
    
    // Auth
    login: "Accedi",
    signup: "Registrati",
    email: "Email",
    password: "Password",
    confirmPassword: "Conferma Password",
    logout: "Esci",
    alreadyHaveAccount: "Hai già un account?",
    dontHaveAccount: "Non hai un account?",
    signupSuccess: "Account creato con successo!",
    loginSuccess: "Accesso effettuato!",
    invalidCredentials: "Email o password non validi",
    passwordsNotMatch: "Le password non corrispondono",
    emailRequired: "Email richiesta",
    passwordRequired: "Password richiesta",
    passwordMinLength: "La password deve essere di almeno 6 caratteri",
    
    // Dashboard
    myQuestionnaires: "I Miei Questionari",
    createNew: "Crea Nuovo Questionario",
    active: "Attivo",
    inactive: "Inattivo",
    expired: "Scaduto",
    responses: "Risposte",
    edit: "Modifica",
    delete: "Elimina",
    activate: "Attiva",
    deactivate: "Disattiva",
    copyLink: "Copia Link",
    extendExpiration: "Estendi Scadenza",
    viewResponses: "Visualizza Risposte",
    createdOn: "Creato il",
    expiresOn: "Scade il",
    noExpiration: "Nessuna scadenza",
    noQuestionnaires: "Nessun questionario",
    createFirstQuestionnaire: "Crea il tuo primo questionario per iniziare",
    deleteConfirm: "Elimina Questionario",
    deleteConfirmMsg: "Sei sicuro di voler eliminare questo questionario? Questa azione non può essere annullata.",
    linkCopied: "Link copiato!",
    linkCopiedDesc: "Il link del questionario è stato copiato negli appunti",
    surveyDeleted: "Questionario eliminato",
    surveyActivated: "Questionario attivato",
    surveyDeactivated: "Questionario disattivato",
    
    // Survey
    submitSurvey: "Invia Questionario",
    requiredField: "Questo campo è obbligatorio",
    surveyExpired: "Questo questionario è scaduto",
    thankYou: "Grazie!",
    responseSubmitted: "La tua risposta è stata inviata",
    surveyNotFound: "Questionario non trovato",
    surveyNotFoundDesc: "Il questionario che stai cercando non esiste o è stato rimosso",
    surveyInactive: "Questionario Inattivo",
    surveyInactiveDesc: "Questo questionario non accetta più risposte",
    submitting: "Invio in corso...",
    
    // Save Survey
    saveSurvey: "Salva Questionario",
    updateSurvey: "Aggiorna Questionario",
    surveyTitle: "Titolo",
    surveyTitlePlaceholder: "Inserisci il titolo del questionario",
    surveyDescription: "Descrizione",
    surveyDescriptionPlaceholder: "Inserisci la descrizione del questionario (opzionale)",
    expirationDate: "Data di Scadenza (opzionale)",
    customExpirationMessage: "Messaggio di Scadenza Personalizzato (opzionale)",
    customExpirationPlaceholder: "Questo questionario è scaduto",
    quickOptions: "Opzioni Rapide",
    days7: "7 giorni",
    days30: "30 giorni",
    noExpirationOption: "Nessuna scadenza",
    surveySaved: "Questionario salvato!",
    surveySavedDesc: "Il tuo questionario è stato salvato con successo",
    surveyUpdated: "Questionario aggiornato!",
    titleRequired: "Titolo richiesto",
    titleRequiredDesc: "Inserisci un titolo per il questionario",
    expirationExtended: "Scadenza estesa",
    expirationRemoved: "Scadenza rimossa",
    pickDate: "Scegli una data",
    selectExpirationDate: "Seleziona data di scadenza",
    removeExpiration: "Rimuovi Scadenza",
    
    // Responses
    surveyResponses: "Risposte Questionario",
    submittedAt: "Inviato il",
    noResponses: "Nessuna risposta",
    noResponsesDesc: "Questo questionario non ha ancora ricevuto risposte",
    exportResponses: "Esporta Risposte",
    responsesExported: "Risposte esportate!",
    
    // Survey Generator
    backToHome: "Torna alla Home",
    createYourSurvey: "Crea il Tuo Sondaggio",
    sections: "sezioni",
    section: "sezione",
    totalQuestions: "domande totali",
    surveyLanguage: "Lingua del Questionario",
    sectionName: "Nome Sezione",
    sectionNamePlaceholder: "Esempio: Informazioni personali, Soddisfazione del cliente, Feedback sul prodotto...",
    questionDescription: "Descrizione Domande",
    questionDescriptionPlaceholder: "Esempio: Crea domande sulla qualità del prodotto, velocità di consegna e servizio clienti...",
    uploadDocument: "Carica Documento",
    chooseFile: "Scegli File",
    clear: "Cancella",
    supportsFiles: "Supporta file PDF, Word e CSV",
    csvImported: "CSV Importato",
    imported: "importate",
    invalidCSV: "CSV Non Valido",
    csvMustHaveData: "Il file CSV deve contenere dati",
    invalidCSVFormat: "Formato CSV Non Valido",
    csvMissingColumns: "Il CSV deve avere le colonne Section, Question e Type",
    importFailed: "Importazione Fallita",
    failedToImportCSV: "Impossibile importare il file CSV",
    generateFirstSection: "Genera Prima Sezione",
    addNewSection: "Aggiungi Nuova Sezione",
    generating: "Generazione in corso...",
    yourSurvey: "Il Tuo Questionario",
    downloadCSV: "Scarica CSV",
    clearAll: "Cancella Tutto",
    removeSection: "Rimuovi Sezione",
    question: "Domanda",
    type: "Tipo",
    multipleChoice: "Scelta multipla",
    checkboxes: "Caselle di controllo",
    shortAnswer: "Risposta breve",
    paragraph: "Paragrafo",
    dropdown: "Menu a discesa",
    required: "Obbligatorio",
    options: "Opzioni",
    addOption: "Aggiungi Opzione",
    save: "Salva",
    fileUploaded: "File caricato",
    fileReady: "è pronto per essere elaborato",
    invalidFileType: "Tipo di file non valido",
    uploadPDFOrWord: "Carica un documento PDF o Word",
    inputRequired: "Input richiesto",
    provideDescription: "Fornisci una descrizione o carica un documento",
    sectionNameRequired: "Nome sezione richiesto",
    provideSectionName: "Fornisci un nome per questa sezione",
    sectionAdded: "Sezione aggiunta!",
    questionsAdded: "domande aggiunte a",
    generationFailed: "Generazione fallita",
    failedToGenerate: "Impossibile generare il sondaggio. Riprova.",
    csvExported: "CSV esportato!",
    importToGoogleForms: "Importa questo file in Google Forms",
    sectionRemoved: "Sezione rimossa",
    hasBeenRemoved: "è stata rimossa",
    allSectionsCleared: "Tutte le sezioni cancellate",
    surveyReset: "Il sondaggio è stato resettato",
    questionUpdated: "Domanda aggiornata",
    changesSaved: "Le modifiche sono state salvate",
    questionDeleted: "Domanda eliminata",
    questionRemoved: "La domanda è stata rimossa",
    feedbackLabel: "Feedback per questa domanda",
    feedbackPlaceholder: "Esempio: Rendi questa domanda più specifica, aggiungi più opzioni, cambia la formulazione...",
    feedbackHelp: "Questo feedback ti aiuta a capire come le domande dovrebbero essere modificate e può essere usato come modello per altre domande.",
    feedbackSaved: "Feedback salvato",
    feedbackSavedDesc: "Il tuo feedback è stato salvato per questa domanda",
    generateMore: "Genera altre domande",
    newQuestionsAdded: "nuove domande aggiunte a questa sezione",
    applyFeedback: "Applica Feedback",
    extendToOthers: "Estendi ad Altre Domande",
    selectAll: "Seleziona Tutto",
    deselectAll: "Deseleziona Tutto",
    questionsSelected: "domande selezionate",
    applying: "Applicazione...",
    applyingFeedback: "Applicazione feedback...",
    feedbackApplied: "Feedback applicato",
    feedbackAppliedDesc: "Le domande sono state rigenerate",
    cancel: "Annulla",
    noFeedback: "Nessun feedback",
    noFeedbackDesc: "Aggiungi un feedback prima di applicarlo",
    questionsUpdated: "domande aggiornate",
    sourceQuestion: "Sorgente",
    newSectionName: "Nome Nuova Sezione",
    addSection: "Aggiungi Sezione",
    hasBeenCreated: "è stata creata",
    newSectionDialogDesc: "Genera una nuova sezione con l'AI fornendo un titolo e un argomento.",
    generateSection: "Genera Sezione",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};